DB接続とGormの導入
NUTFes/lottery pull request #231
Opened 2022-10-12 22:03 UTC by TsubasaOura

## 概要

resolve #220

## テスト項目

- `docker compose up` 可能か
- `docker compose up` を実行すると，テスト用に作ったmysqlにusersカラムが追加されるか

*確認方法*
```bash
docker compose up -d
docker compose run --rm db bash
mysql -u gomysql -h db -p
Enter password: password

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| gomysql            |
| information_schema |
| performance_schema |
+--------------------+
3 rows in set (0.01 sec)

mysql> use gomysql;

mysql> show tables;
+-------------------+
| Tables_in_gomysql |
+-------------------+
| users             |
+-------------------+

2022-10-13 09:38 UTC, hikahana approved these changes, later dismissed
userカラムの追加確認できました！

2022-10-14 15:22 UTC, ryuseifujisaki commented
@TsubasaOura 
DB接続との確認はできました。
ただ、なぞのファイルが`mysql/data`以下に追加されたんですけどこれわかります？
![image](https://user-images.githubusercontent.com/50622120/195882846-ec92f7cf-3c3a-475a-b7d9-e62c75950561.png)

2022-10-14 15:22 UTC, ryuseifujisaki requested changes

2022-10-14 15:22 UTC, ryuseifujisaki commented on go_api/infrastructure/sqlhandler.go
> +	"os"
```suggestion
  "os"
```
ここスペースじゃなくタブが入ってますね

2022-10-14 15:22 UTC, ryuseifujisaki commented on go_api/infrastructure/sqlhandler.go
> +	"api/interfaces/database"
```suggestion
  "api/interfaces/database"
```
ここもスペースにしましょう

2022-10-14 15:22 UTC, ryuseifujisaki commented on go_api/interfaces/database/sql_handler.go
> +}
```suggestion
}

```
最後空行をお願いします

2022-10-14 15:22 UTC, ryuseifujisaki commented on go_api/interfaces/database/user_repository.go
> +}
```suggestion
}

```
ここも空行お願いします

2022-10-14 15:22 UTC, ryuseifujisaki commented on go_api/server.go
> +}
```suggestion
}

```
空行をお願いします

2022-10-19 05:20 UTC, ryuseifujisaki approved these changes

2022-10-19 05:20 UTC, merged