[add]各モデルdomainの追加を行いました(#237)
NUTFes/lottery pull request #238
Opened 2022-10-19 08:10 UTC by hikahana

## 概要

resolve #237 
domainモデルの作成をしました。

## 画面スクリーンショット等

- `URL`
- スクリーンショット

## テスト項目

-コードに間違いがないか確認をお願いします。
-
-

## 備考

2022-10-24 13:34 UTC, TsubasaOura commented on go_api/domain/event.go
> +	Name      int       `json:"name" gorm:"not null"`
Nameはstringになるかと思います！

2022-10-24 13:34 UTC, TsubasaOura commented on go_api/domain/event_user.go
> +}
`event_user.go`はGormの`many2many`の機能を使用すればいらなくなる可能性があります！

2022-10-24 13:34 UTC, TsubasaOura commented on go_api/server.go
> +  db.Migrator().CreateTable(domain.Event_user{})
`many2many`によって必要なくなる可能性あります

2022-10-24 13:34 UTC, TsubasaOura commented on go_api/server.go
> +  db.Migrator().CreateTable(domain.Winner{})
server.goにどんどん追記していくと肥大化してしまうため
別ファイルに分けてもよいかもです
https://github.com/jphacks/B_2206/blob/develop/backend/cmd/init.go

2022-10-24 13:35 UTC, TsubasaOura approved these changes, later dismissed

2022-10-25 04:52 UTC, ryuseifujisaki requested changes
あとは大浦くんと同じですかね。
少しだけコードを成形したら良さげですね！

2022-10-25 04:52 UTC, ryuseifujisaki commented on go_api/domain/admin.go
> +}
```suggestion
}

```
最後の行は空行入れましょう！いくつか見られるので修正お願いします
自動で最後に入れる機能がVscodeにはあるので設定していなかったら設定を推奨します！
https://memo.koumei2.com/vscode-%E3%81%AE%E6%94%B9%E8%A1%8C%E9%96%A2%E9%80%A3%E3%81%AE%E5%9F%BA%E6%9C%AC%E8%A8%AD%E5%AE%9A/

2022-10-25 04:52 UTC, ryuseifujisaki commented on go_api/server.go
> +  "gorm.io/driver/mysql"
おそらく昨日入れた自動成形を使えば
```suggestion
"gorm.io/driver/mysql"
```
スペースからタブになるはず

2022-10-27 13:01 UTC, ryuseifujisaki requested changes

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/dbinit.go
> +	db.Migrator().CreateTable(domain.User{})
```suggestion
	db.AutoMigrate(domain.User{})
```
下の4つのやつも同じですが、`db.AutoMigrate(domain.User{})`このようにしないと中間テーブルとかは自動生成されないかと思います

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/domain/admin.go
> +	ID        int       `json:"id" gorm:"primary_key;not null"`
```suggestion
	ID        uint       `json:"id" gorm:"primary_key;not null"`
```
ここは`uint`のほうが適切かもしれないですね

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/domain/event.go
> +	ID        int       `json:"id" gorm:"primary_key;not null"`
```suggestion
	ID        uint       `json:"id" gorm:"primary_key;not null"`
```
ここも`uint`

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/domain/user.go
> +	ID        int       `json:"id" gorm:"primary_key"`
```suggestion
	ID        uint       `json:"id" gorm:"primary_key"`
```
上に同じ

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/domain/user.go
> +	Numeber   int       `json:"number" gorm:"unique;not null"`
```suggestion
	Numeber   uint       `json:"number" gorm:"unique;not null"`
```

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/domain/winner.go
> +	ID        int       `json:"id" gorm:"primary_key;not null"`
```suggestion
	ID        uint       `json:"id" gorm:"primary_key;not null"`
```

2022-10-27 13:01 UTC, ryuseifujisaki commented on go_api/dbinit.go
> +
```suggestion
var (
	db  *gorm.DB
	err error
	dsn = os.Getenv("DSN")
)

func main() {
	dbinit()
}
```
`server.go`15行目の変数定義はここにあったほうがいいですね。
とgoloangは`main`関数が必須なので`main`関数で`dbinit()`を呼ぶ形でいいですね
あと`main`関数を作るとserver.goの`main`関数とダブルので`go_api/cmd/dbinit.go`の中に入れてあげると適切に動くと思われます

2022-10-28 16:21 UTC, ryuseifujisaki requested changes
package mainとuintだけ直せばmergeできそうですね

2022-10-28 16:21 UTC, ryuseifujisaki commented on go_api/cmd/initdb.go
> +package cmd
```suggestion
package main
```
惜しい！
ここは`package main`で大丈夫です。

2022-10-29 01:00 UTC, TsubasaOura reviewed
yosa

2022-10-29 07:11 UTC, ryuseifujisaki approved these changes
問題ないと思います！

2022-10-29 07:12 UTC, merged