Dev/issue233
NUTFes/lottery pull request #244
Opened 2022-11-04 01:31 UTC by ryuseifujisaki

## 概要

resolve #233 
**アーキテクチャ構成の見直し** 4f9f9f83e355023671d9f3e3d58949ed9e0185b2
**UserのCRUD作成** 0c1dc9a9655a5170de37ffd4d5e981d49108387c
-  `domain`にはEntityとrepositoryを記述
- `infrastructure`にはDB操作(gorm)
- `usecase`には処理
- `controller`ではusecaseを呼び出している。
- `main.go`には依存関係と`router`を記述した。

FinanSuと違う点
- Gormを使うことで、DB操作を簡単にしている点
- routerや依存関係の記述をmainに書いている点

`UserのAPI情報の追記` 8cc1a6ade0de2bd74b57e41835d148100a3355e6
- `server.go`では`swag i`がうまく動かなかったので、`main.go`に修正
- `docs.go`にUserのAPI情報を記述

## 画面スクリーンショット等

- `URL`
`http://localhost:1323/swagger/index.html#/`
- スクリーンショット
![image](https://user-images.githubusercontent.com/50622120/199865387-eed7a50a-db87-4e80-864d-d83df9d09028.png)

## テスト項目

- アーキテクチャをこれで良いか、クリーンアーキテクチャにするか
- `http://localhost:1323/swagger/index.html#/`でAPIドキュメントを確認できるか
- `User`のCRUDの動作確認をswagger UI上で確認する

## 備考
`main.go`に依存関係と`router`を書いたので今後肥大化する可能性がある。そのため、今後のタスクとして、切り分けを行なっても良いかもです。

2022-11-05 01:37 UTC, hikahana requested changes
空白あったのでコードの修正だけお願いします。

2022-11-05 01:37 UTC, hikahana commented on go_api/domain/user.go
> +	Number    uint64      `json:"number" gorm:"unique;not null"`
```suggestion
	Number    uint64    `json:"number" gorm:"unique;not null"`
```
空白があったので修正お願いします。

2022-11-07 12:17 UTC, TsubasaOura approved these changes, later dismissed

2022-11-07 12:22 UTC, TsubasaOura approved these changes

2022-11-07 12:23 UTC, hikahana approved these changes
おけまるです

2022-11-07 12:24 UTC, merged