eventのCRUD作成
NUTFes/lottery pull request #255
Opened 2022-11-14 12:54 UTC by TsubasaOura

## 概要

resolve #235

## 画面スクリーンショット等

- `http://localhost:1323/swagger/index.html`

## テスト項目

- Swaggerを用いてCRUDが動作することを確認

## 備考

2022-11-14 16:06 UTC, ryuseifujisaki requested changes
動作確認はしたのでコメントしたところの修正をお願いします

2022-11-14 16:06 UTC, ryuseifujisaki commented on go_api/infrastructure/event.go
> +}
```suggestion
func (e *EventInfrastructure) FindAll() (*domain.Events, error) {
	events := domain.Events{}
	if err := e.db.Find(&events).Error; err != nil {
		return nil, err
	}
	return &events, nil
}
```
レシーバーの値が`u`のままなので`e`に変更お願いします。

2022-11-14 16:06 UTC, ryuseifujisaki commented on go_api/infrastructure/event.go
> +}
ここもレシーバーの値を修正

2022-11-14 16:06 UTC, ryuseifujisaki commented on go_api/interfaces/event_controller.go
> +}
```suggestion
func NewEventController(eu usecase.EventUsecase) EventController {
	return &eventController{eventUsecase: eu}
}
```
ここも正しくは`eu` ですかね

2022-11-14 16:06 UTC, ryuseifujisaki commented on go_api/interfaces/event_controller.go
> +}
このファイルもレシーバーの値を修正

2022-11-14 16:06 UTC, ryuseifujisaki commented on go_api/usecase/event_usecase.go
> +}
```suggestion
func NewEventUsecase(eu domain.EventRepository) EventUsecase {
	return &eventUsecase{eventRepository: eu}
}
```
このファイルもレシーバーの値を修正する

2022-11-16 13:56 UTC, TsubasaOura commented
修正しました！

2022-11-20 15:09 UTC, ryuseifujisaki approved these changes, later dismissed
LGTM

2022-11-21 08:41 UTC, ryuseifujisaki approved these changes
コンフリクト解消

2022-11-21 08:41 UTC, merged