[add]EventParticpantCardコンポーネントの作成(#302)
NUTFes/lottery pull request #320
Opened 2023-03-09 07:26 UTC by hikahana

## 概要
EventParticpantCard(参加者一覧table)のコンポーネントを作成しました。

resolve #302

## 画面スクリーンショット等

- `URL`
- スクリーンショット
<img width="957" alt="image" src="https://user-images.githubusercontent.com/106811268/223948578-e6f5f0df-44d1-48f9-8a4d-fa6d501b5c45.png">

## テスト項目

-`localhost:3000/home`にアクセスしてスクショみたいな感じにテーブルが表示されているか確認お願いします。
-
-

## 備考
-動くけど型のところでエラーがあって直し方わからなかったので知ってたら教えてください。
-domain/event.go(user.go)のjson部分にsがついてないのでちょっとややこしくなりそうです。今のうちに修正してもいいかもです。下記の部分です。
<img width="531" alt="image" src="https://user-images.githubusercontent.com/106811268/223948964-f14383ed-584e-4796-b8d0-53b187069c6f.png">

2023-03-11 07:04 UTC, ryuseifujisaki requested changes, later dismissed

2023-03-11 07:04 UTC, ryuseifujisaki commented on docker-compose.yml
>      tty: true
自分で差分を書き込んだ感じですよね？
rebaseで差分を取り込んだ方がいいと思います。

2023-03-11 07:04 UTC, ryuseifujisaki commented on view/next.config.js
> +  }
これもrebaseで取り込んだ方が良さそう

2023-03-11 07:04 UTC, ryuseifujisaki commented on go_api/main.go
> +	// "os"
このファイルもrebaseで取り込んだ方が良さそうです

2023-03-11 07:06 UTC, ryuseifujisaki commented
main.goなどのファイルはrebaseで取り込んだ方がいいかなと思います。
わからなければ、教えます

2023-03-11 07:06 UTC, ryuseifujisaki commented
デザインとかは藤崎的には良さげだと思います

2023-03-11 12:35 UTC, imaimai17468 reviewed
いい感じです！！
命名規則や細かい修正について指摘したので修正お願いします〜
`いや、これは意味があってこうしたんや！`って場合は修正しなくて大丈夫です
また、eventのidはpropsから受け取りたいので、それについてのレビューも書きました！

最後に諸々コンフリクトが起きてるので、rebaseかpullして解消しましょう！

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +const EventParticpantCard = () => {
スペルミスですね
（これ変えると他のファイル名とか全部変える必要があって大変ですが頑張ってください）

```suggestion
const EventParticipantCard = () => {
```

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +  const [eventusers, setEventUsers] = useState<Events[]>()
setEventUsersに合わせてキャメルケースにしましょう！
また、受け取るのはEvent単体なので、配列じゃなくて大丈夫です！

```suggestion
  const [eventUsers, setEventUsers] = useState<Events>()
```

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +interface Events {
この型はEvent単体の型なので、単数でいきましょう！

```suggestion
interface Event {
```

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +  const [eventusers, setEventUsers] = useState<Events[]>()
そもそも受け取るのはeventUsersではなくevent単体なので、

`const [event, setEvent] = useState<Events>()`

が丸いと思います！

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +    setRowsPerPage(+event.target.value);
+でNumberに型推論されるの初めて知った
参考：https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Unary_plus

すごいけどわかりにくいので、Number関数でラップして型変換しましょう！

```suggestion
    setRowsPerPage(Number(event.target.value));
```

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +              <TableCell align="left">
alignはデフォルトでleftなので指定しなくても大丈夫だと思います！
69行目の学籍番号も同様です〜

```suggestion
              <TableCell>
```

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +    fetch(process.env.CSR_API_URI + '/events/7/users', {
ここは直接値を入れるのではなく、propsから取って来たいです
propsはcomponentの引数みたいなもので、そのcomponentを使ってる親から値を受け取ることができます！
手順を示します。

1.` common/EventParticipantCard/`内に`EventParticipantCard.type.ts`を作成
2. propsの型定義をそのファイルに書く

```
export interface EventParticipantCardProps {
    eventId: string;
}
```

これぐらいだったら直接`EventParticipantCard.tsx`に書けばいいじゃん！と思うかもしれませんが、propsで取ってきたい変数が増えるほど別ファイルに定義したほうが綺麗になります！

また、`User`や`Event`みたいな型定義も`EventParticipantCard.type.ts`に書いたほうが綺麗になります！そうするなら、`.type.ts`じゃなく`.types.ts`にしたほうが意味が近いのでそうしましょう！

3. `EventParticipantCard.tsx`でimport

```
import { EventParticipantCardProps } from './EventParticipantCard.type';
```

4. EventParticipantCardにpropsを与える

```
const EventParticipantCard = (props: EventParticipantCardProps) => {
```

5. fetchしたい行でpropsを使う

```suggestion
    fetch(process.env.CSR_API_URI + `/events/${props.eventId}/users`, {
```

バッククォートの中に`${}`で変数を囲むと文字列の中に組み込むことができます！

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/layout/MainLayout/MainLayout.tsx
> +      <EventParticpantCard  />
event idをpropsで受け取る場合以下のようになります！！

```suggestion
      <EventParticipantCard eventId='1' />
```

↑これも実際は`1`じゃなく、そのページからidを取得して変数を受け取る形になりますが、今はとりあえず1を入れています。

2023-03-11 12:35 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +  user: User[]
ここもできればUserの配列なのでusersにしたいですが、バックエンド側の変更が必要なので、自分の作業量と相談して決めてください〜

```suggestion
  users: User[]
```

2023-03-11 15:09 UTC, imaimai17468 commented on view/src/components/common/EventParticpantCard/EventParticpantCard.tsx
> +        count={eventusers?.user.length}
countはundefinedを許容しないのでエラーが出てますね
undefinedの時は0などの初期値を入れておくといいです！

```suggestion
        count={eventusers?.user.length || 0}
```

`?`はoptional Chainingといって、nullやundefinedな呼び出しを可能とする記号です
eventusersがundefinedだと結果全体はundefinedとなるので、numberしか許容しないcountでエラーが出るわけです
参考：https://qiita.com/ryo2132/items/12981f61db21112cb61c#---optional-chaining--

`eventusers?.user.length || 0`でundefinedの時なぜ0に確定するかというと、or論理式の短絡評価があるためです。
`const x = a || b` としたとき、orなので片方が真の時点でtrueになります。
なのでaがtrueの時はtrueで確定するためaを返し、aがfalseの時はbによって真偽値が確定するためbを返します。
この時true/falseを返すのではなく、a/bの値を返すため、今回`eventusers?.user.length || 0`とすることで、左辺がundefinedの時は0が返ってくるわけです。
参考：https://zenn.dev/fujii0112/articles/78fe69c4c30731#%E2%97%87-%E5%9F%BA%E6%9C%AC-1

2023-03-21 06:31 UTC, TsubasaOura approved these changes
修正しました

2023-03-21 06:32 UTC, merged